# Generated by Django 4.1.3 on 2022-11-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
    ]
